# netlify.toml
[build]
  # Commande pour build avec preset netlify
  command = "npm run build"
  # Avec preset netlify, pas besoin de spécifier publish, Nuxt s'en charge
  # Dossier des fonctions Netlify (priorité sur les fonctions internes Nuxt)
  functions = "netlify/functions"

[build.environment]
  # Variables pour build
  NODE_VERSION = "18"

[dev]
  # Configuration pour le développement local avec Netlify CLI
  command = "npm run dev"
  targetPort = 3000

# Redirections spécifiques pour nos fonctions Netlify personnalisées
# IMPORTANT: Ces redirections sont testées dans l'ordre, les plus spécifiques d'abord

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/api/youtube-netlify"
  to = "/.netlify/functions/youtube-scraper"
  status = 200
  force = true

# Note: 
# - Les fonctions personnalisées sont dans netlify/functions/ (configuré ci-dessus)
# - Avec preset netlify, Nuxt génère automatiquement les redirections nécessaires
# - Pas besoin de redirections manuelles pour le routing Nuxt ou les API routes