# netlify.toml
[build]
  # Commande pour build avec preset netlify
  command = "npm run build"
  # Le dossier de sortie pour les fichiers statiques (preset netlify)
  publish = ".output/public"
  # Dossier des fonctions Netlify (priorité sur les fonctions internes Nuxt)
  functions = "netlify/functions"

[build.environment]
  # Variables pour build
  NODE_VERSION = "18"

[dev]
  # Configuration pour le développement local avec Netlify CLI
  command = "npm run dev"
  targetPort = 3000

# Redirections spécifiques pour nos fonctions Netlify personnalisées
# IMPORTANT: Ces redirections sont testées dans l'ordre, les plus spécifiques d'abord

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/api/youtube-netlify"
  to = "/.netlify/functions/youtube-scraper"
  status = 200
  force = true

# PAS de redirection catch-all - laisser Nuxt/Nitro gérer le routage SPA/SSR automatiquement
# Le preset netlify de Nuxt configure automatiquement les redirections nécessaires

# Note: 
# - Les fonctions Nuxt API routes sont dans .netlify/functions-internal/ (automatique)
# - Nos fonctions personnalisées sont dans netlify/functions/ (configuré ci-dessus)
# - Nuxt gère automatiquement le fallback pour les routes SPA