# netlify.toml
[build]
  # Commande pour build avec support des fonctions séparées
  command = "npm run build"
  # Le dossier de sortie pour les fichiers statiques (avec node-server preset)
  publish = ".output/public"
  # Dossier des fonctions Netlify (priorité sur les fonctions internes Nuxt)
  functions = "netlify/functions"

[build.environment]
  # Variables pour build
  NODE_VERSION = "18"

[dev]
  # Configuration pour le développement local avec Netlify CLI
  command = "npm run dev"
  targetPort = 3000

# Redirections pour forcer Netlify à utiliser nos fonctions au lieu de Nuxt
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/api/youtube-netlify"
  to = "/.netlify/functions/youtube-scraper"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Note: Avec Nuxt + preset netlify, les fonctions sont automatiquement dans .netlify/functions-internal/
# et Netlify les détecte automatiquement, pas besoin de configuration explicite

# Laisser Nuxt/Nitro gérer le routage automatiquement
# Les redirections manuelles peuvent interférer avec les API routes